### ISSUE TITLE
Old 1.2.0 version on AMO

### ISSUE THREAD

**Issue by gioxx** [doma-itachi/Youtube-shorts-block#13]
Just curious: why on AMO I can find the old 1.2.0 version? Do you have problems with 1.3.1+ update approval? 😯 
Thanks! :slightly_smiling_face:

**Comment by azalty** [comment]
Wondering the same thing

**Comment by azalty** [comment]
Wondering the same thing @doma-itachi

**Comment by doma-itachi** [comment]
v1.3.4(1.3.3) for Firefox (86f38822eb6f643fccdcf748722fd2acc7d2f2fe) has been submitted for review! (AMO is too hard to use)
https://github.com/doma-itachi/Youtube-shorts-block/releases/tag/v1.3.3Fx
![image](https://user-images.githubusercontent.com/94786908/200336209-43ca3219-1756-48be-a36c-a0c554f9417d.png)

To run on Firefox, you need to rewrite the code written in Manifest v3 to Manifest v2.

**Comment by gioxx** [comment]
I usually prefer to use AMO! If you find it so difficult and want a hand just ask, I can maintain the version on AMO for you 😄 
In the meantime thanks! I'll wait the official version from AMO.
