### ISSUE TITLE
Chrome extension stopped working

### ISSUE THREAD

**Issue by MemLiveOn** [doma-itachi/Youtube-shorts-block#17]
Please update the chrome webstore extension. It no longer redirects as it is supposed to. Just plays the shorts UI. Tried disabling and reenabling, and reloading the page. Same behavior. Also chromium browsers no longer let us install third party extensions, so installing from github is impossible (not talking about firefox, just Chrome or Brave or other chromium browsers).

**Comment by doma-itachi** [comment]
We could not confirm the issue of no redirection in Youtube-shorts block v1.3.3(latest), Chrome108.
However, under certain circumstances, this problem can occur.
If you could tell us the following, we might be able to solve the problem. (as much as you can answer)
- The region (country) you are accessing
- The URL before the redirect (like https://www.youtube.com/shorts/"videoID")
- Are there any errors from this extension in the console(DevTools) (please give me a screenshot)
- Are extensions enabled
![image](https://user-images.githubusercontent.com/94786908/209486920-3b49f688-1b4f-481d-a276-c8a134ebb841.png)

**Comment by MemLiveOn** [comment]
The extension started working perfectly fine today. Apologies.
