### ISSUE TITLE
No extension options?

### ISSUE THREAD

**Issue by jangxx** [doma-itachi/Youtube-shorts-block#26]
A recent update turned the "Hide Shorts Video" option on by default with a note saying that we can turn it back off in the options. My problem is now, that I can't find those options anywhere.

The dropdown menu when clicking on the extension icon does not contain the entry "Options" like it does in other extensions that have options:

![options button](https://i.imgur.com/aOvC6r9.png)

The actual extension settings also don't have an options button:

![extension page](https://i.imgur.com/5VCK0ga.png)

Now I'm wondering if the options actually hide somewhere else or if there is a bug in version 1.4.0 that makes them not show up. Either way I would like to disable this option again, since I don't mind having shorts in my subscription feed.

**Comment by doma-itachi** [comment]
Thank you for your feedback.
Please refer to the image below for disabling ;)

![image](https://user-images.githubusercontent.com/94786908/226177683-4462ecb0-da7b-4707-b7f0-5f6cbdb9b70d.png)
![image (1)](https://user-images.githubusercontent.com/94786908/226177687-ad997ddb-af64-4384-8fe5-afbda9117d61.png)
![image (2)](https://user-images.githubusercontent.com/94786908/226177689-c83a91da-926f-4a61-88fa-875ffe881123.png)
![image (3)](https://user-images.githubusercontent.com/94786908/226177690-f6698276-a9f7-437e-92fd-47a9a38d6312.png)

( I'm planning to post a guide about disabling, but I'm thinking about how to guide users to the guide... )

**Comment by jangxx** [comment]
Ah I see, thanks. That worked no problem.
