### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by younesaassila** [doma-itachi/Youtube-shorts-block#3]
Do you plan on adding this extension to the Firefox Add-ons Store? It would be really useful :)

**Comment by doma-itachi** [comment]
I'd like to release it to Firefox right now, but firefox does not support Manifest v3, so minor modifications are needed.
Please wait a little. Thanks!
(Sorry for the machine translation)

**Comment by doma-itachi** [comment]
The Firefox version has been released!
https://addons.mozilla.org/addon/youtube-shorts-block/
