### ISSUE TITLE
Latest Firefox Version is 1.3.4

### ISSUE THREAD

**Issue by jtl001** [doma-itachi/Youtube-shorts-block#35]
I'm not sure if this has been discussed before, but the latest version available on Firefox is 1.3.4 from November 2022. This is far behind the Chrome version.

**Comment by doma-itachi** [comment]
v1.4.1(latest) is currently under review and will be released as soon as it passes!
Please wait a moment ;)
![image](https://github.com/doma-itachi/Youtube-shorts-block/assets/94786908/1220ca0e-0b9a-487f-b7a4-bbd4d87018a5)
