### ISSUE TITLE
New Short Section in the subscription page

### ISSUE THREAD

**Issue by OshidaBCF** [doma-itachi/Youtube-shorts-block#40]
Youtube just added a short section in the subscription page
![image](https://github.com/doma-itachi/Youtube-shorts-block/assets/61458287/15a3b760-a5bb-46b8-9c1e-c113bcf40cd5)

They really want us to watch those stupid shorts...

Luckly it's easily hidable with an adsblocker, but maybe you can integrate this in your extension

**Comment by doma-itachi** [comment]
Thanks for the report!
If you don't mind, could you give me the code for the filter?

**Comment by OshidaBCF** [comment]
I just noticed a mistake with my filter but it's not that much a problem

So the one i used with µBlock Origin is `##.ytd-rich-section-renderer.style-scope`

Combined with your extension that already hides the shorts themselves, the filter was hidden what's in red in this picture (your extension is already hiding all the shorts)
![image](https://github.com/doma-itachi/Youtube-shorts-block/assets/61458287/cb0d56d8-8de5-4181-9848-96ad4feaa9c6)

So it hides the little "bar", but it also hide the little buttons at the top

For me it doesn't really matter as i never use those top buttons, but it might cause problem for other users

So i tried other filters and this one only hide the short "shelf", but it use a "nth" selector which i don't really like because it's heavily dependent of the order, although it shouldn't cause any issue on this page

`##ytd-rich-section-renderer.ytd-rich-grid-renderer.style-scope:nth-of-type(2)`

Fell free to add it to your extension

**Comment by wdebsqi** [comment]
I think it's already handled in [main.js](https://github.com/doma-itachi/Youtube-shorts-block/blob/master/src/main.js#L158C10-L158C10). I checked and it looks like the `removeShortVideo()` function successfully removes the "shorts" section from the subscription page (at least in my Browser - `Brave v.1.6.114`).

@OshidaBCF can you check if the issue still occurs? If so, I can try to fix it.

**Comment by OshidaBCF** [comment]
Yeah it doesn't occurs anymore

So it's fixed
