### ISSUE TITLE
New UI update doesn't hide Shorts page in the channel's page

### ISSUE THREAD

**Issue by mrkrabs206** [doma-itachi/Youtube-shorts-block#44]
Hey, the new UI update by YouTube itself made a new **You tab** , which replaced the old Library tab. This is the worst one in YouTube history, like WHY?!?!?! Also, the update made on channel page, that the "Shorts" page does not hide anymore. Please make an update on this right now.
![GTA Series Videos - YouTube - Google Chrome 10_28_2023 16_06_39](https://github.com/doma-itachi/Youtube-shorts-block/assets/110676833/6837fc2e-cf7a-4c5e-a56d-090665802b92)

**Comment by mrkrabs206** [comment]
HEEEEEELLLLLLLLOOOOOO

**Comment by noah-frank** [comment]
@mrkrabs206 Bro are you serious? This is a free add-on and it's weekend. Write the update yourself or ask nicely if the developer finds the time to update this add-on.

**Comment by mrkrabs206** [comment]
> @mrkrabs206 Bro are you serious? This is a free add-on and it's weekend. Write the update yourself or ask nicely if the developer finds the time to update this add-on.

I dont know how lol

**Comment by mrkrabs206** [comment]
> > @mrkrabs206 Bro are you serious? This is a free add-on and it's weekend. Write the update yourself or ask nicely if the developer finds the time to update this add-on.
> 
> I dont know how lol

???

**Comment by EduartePaiva** [comment]
I think that if you are going all the way to the short tab inside of a YouTube channel, then it's not a matter of distraction anymore so I don't think that this addon should address that because it's not the purpose of it
