### ISSUE TITLE
"hide shorts video" Option does not seem to function on subscriptions page.

### ISSUE THREAD

**Issue by mrhappypenguin** [doma-itachi/Youtube-shorts-block#47]
When signed in, I see the short video section on the subscriptions page. It's on the 3rd row of videos.

As a temporary solution, I've added "youtube.com##ytd-rich-shelf-renderer.style-scope > div:nth-child(1)" to my ublock origin filters. This removes the short video section, but I don't know it breaks anything on Youtube's other pages.

**Comment by doma-itachi** [comment]
I have confirmed this in the Japanese version.
I will patch and modernize the code in the near future.
Thanks!

**Comment by doma-itachi** [comment]
I've added code to block the "ytd-rich-shelf-renderer" for now. https://github.com/doma-itachi/Youtube-shorts-block/commit/2e61b70f0de6e1e737a1be52b7d0c10ef61496b5
By the way, the refactoring isn't done yet🤯
