### ISSUE TITLE
make shorts video thumbnails appear as a regular video thumbnail

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [doma-itachi/Youtube-shorts-block#8]

**Comment by doma-itachi** [comment]
Regular short videos do not have thumbnails. (except for older videos).
Therefore, we believe that the existing thumbnail display is best.

**Comment by doma-itachi** [comment]
We also believe that the Shorts logo in the lower right corner of the thumbnail should not be removed in order to determine whether it is a short or not!

**Comment by doma-itachi** [comment]
Sorry for the machine translation ;)
